### ISSUE TITLE
Orsbourne - netbadge

### ISSUE THREAD

**Issue by ajp9e** [castl350/CANVAS-ECI-SUPPORT#20]
I received the email to register for Canvas, but when I click the link there is not where to register.  I am asked to sign into NetBadge, but there is not an option to create an account.  Any suggestions?

APL sent her url and told her click 'get started' - waiting for her to get back to me

**Comment by ajp9e** [comment]
Hi,
When I click on Get started I get the NetBadge screen as shown below.

**Comment by ajp9e** [comment]
10/12/18 We were emailing last night, but I can't reply to your last email because power outages have knocked out our school email.  

I have tried opening the start here link on multiple computers, multiple types of browsers and my phone with no luck.  Is it possible to send me the direct link?

**Comment by mattsema** [comment]
accessed course with second invitation
